id: P68FAC246
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG4454
  instance_id: http://purl.bdrc.io/resource/IE1KG4454
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - དཔལ་ལྡན་ཆོས་རྗེའི་བདེན་གཉིས་དང་ཞྭ་དམར་དྲང་ངེས་ཟིན་བྲིས་ལེགས་བཤད་སྙིང་པོའི་མཆན་དབྱོར།
  alt_title:
    en-x-mixed:
    - Grub mthaʼ bźiʼi lugs kyi kun rdzob daṅ don dam paʼi don ram par bśad paʼi legs
      bśad dpyid kyi dpal moʼi glu dbyaṅs źes bya ba bźugs so /Khal-kha Ṅag-dbaṅ-dpal-ldan.
      Draṅ ṅes legs bśad sñiṅ poʼi dkaʼ gnad las brtsams paʼi zin bris dpyod ldan
      yid kyi mun sel źes bya bźugs so / Źwā-dmar Paṇḍi-ta Dge-ʼdun-bstan-ʼdzin-rgya-mtsho.
      Legs bśad sñiṅ boʼi mtsan sbyor ma bu skyid ṅo sprod paʼi pho ña źugs so / Rdo-sbis
      Dge-bśed Śes-rab-rgya-mtsho.
  author: http://purl.bdrc.io/resource/P272
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    5b54a272ff7e4baea2665ca7e7dac607:
      title: པོད ༡་དཔལ་ལྡན་ཆོས་རྗེའི་བདེན་གཉིས་དང་ཞྭ་དམར་དྲང་ངེས་ཟིན་བྲིས་ལེགས་བཤད་སྙིང་པོའི་མཆན་དབྱོར
      volume_number: 1
      base_file: UT1KG4454_I1KG4569_0000.txt
      reference: http://purl.bdrc.io/resource/VLF1B93262704007C7
      image_group: I1KG4569
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/W1KG4454
  - http://purl.bdrc.io/resource/MW1KG4454
  ocr_software: Namsel
created_at: '2021-12-22T10:41:48.871332'
last_modified_at: '2021-12-22T10:41:48.871339'
